### ISSUE TITLE
`pipx` install on Kubuntu/Ubuntu/Debian

### ISSUE THREAD

**Issue by mojolo** [jim-easterbrook/Photini#197]
In case it's helpful, this is a fairly straight forward way to build photini in its own virtualenv using `pipx` on Debian-based systems.

Install gphoto2 build dependency via system package manager (`apt`):
```
sudo apt install libgphoto2-dev
```
Install Photini from pypi using `pipx`:

```
pipx install Photini
```
PyQt5 + PyQtWebEngine (or PySide2/PySide6) are required dependencies to run Photini but `pipx` doesn't know it needs to install them into the virtualenv. We can use the `inject` command to accomplish this.

While we're at, we can also `inject` all optional dependencies, which should accomplish the same thing as running `photini-configure` and selecting **Yes** to everything.
```
pipx inject photini PyQt5 PyQtWebEngine requests-oauthlib requests-toolbelt keyring gphoto2 pyenchant gpxpy Pillow
```

>**Sys info**
Kubuntu 23.04

**Comment by jim-easterbrook** [comment]
I've not used `pipx` but I assume you can also install dependencies the same way as with `pip`, for example:
`pipx install photini[flickr,importer,spelling,gpxpy,Pillow,PySide6] `
should install all dependencies. `PySide2` is available as an alternative to `PySide6`, and `PyQt` will be added in the next release (see 198774f).

This isn't a bug in Photini though, so I'll close this issue.
