### ISSUE TITLE
No module named 'photini._version'

### ISSUE THREAD

**Issue by alexpopov** [jim-easterbrook/Photini#210]
Hello! 

I'm trying to run Photini from source and I'm getting `ModuleNotFoundError: No module named 'photini._version'` 

Like the Python interpreter, I also cannot find the `_version` module :^) 

Is there some extra step I need to run prior to `python3 src/run_photini.py`? 

[Followed the docs here.](https://photini.readthedocs.io/en/latest/other/installation.html#development-version)

**Comment by jim-easterbrook** [comment]
Ah, that's something I hadn't spotted when I made changes to the build process to use `pyproject.toml`. The version file is created when you run `pip install` or `python -m build`.

I'll fix it somehow this week.

**Comment by jim-easterbrook** [comment]
I've released version 2023.10.0 which should fix this bug.
