### ISSUE TITLE
Error ModuleNotFoundError: No module named 'cachetools.ttl' with cachetools >= 5.0

### ISSUE THREAD

**Issue by jlprojects** [jim-easterbrook/Photini#244]
I really like photini for tagging my analogue photo scans. 

Using OpenSuSE slowroll, Python 3.11 in a virtual environment. However installing as per ReadtheDocs I always get an error log on start, and the mapping tabs don't work. The error log is:

```
11:35:30: ERROR: photini.pyqt: No module named 'cachetools.ttl'
Traceback (most recent call last):
  File "/home/user/venv/lib64/python3.11/site-packages/photini/pyqt.py", line 190, in wrapper
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/user/venv/lib64/python3.11/site-packages/photini/editor.py", line 468, in add_tabs
    tab['object'] = tab['class'](self.app.image_list)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/venv/lib64/python3.11/site-packages/photini/photinimap.py", line 212, in __init__
    self.geocoder = self.get_geocoder()
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/user/venv/lib64/python3.11/site-packages/photini/googlemap.py", line 102, in get_geocoder
    return GoogleGeocoder(parent=self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/venv/lib64/python3.11/site-packages/photini/photinimap.py", line 55, in __init__
    self.query_cache = pickle.load(f)
                       ^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'cachetools.ttl'
```
Pip currently brings in cachetools 5.3.3 - Googling the error doesn't seem to result any clues, but I did find a reference (which I didn't make a note of and can't find the link now, sorry) that indicates that cachetools.ttl was a hidden API, or deprecated.

Photini works correctly if I force Pip to install a version of cachetools < 5.0.0 - e.g. 

`pip install --force-reinstall -v "cachetools==4.2.4"`

This works as a workaround - so posting here in case it helps anyone else.

**Comment by jim-easterbrook** [comment]
The change log for `cachetools` shows the submodule `ttl` was removed in version 5.0.0, but Photini doesn't directly use `cachetools.ttl` so that shouldn't be a problem.
https://github.com/tkem/cachetools/blob/master/CHANGELOG.rst

Photini started using `cachetools` in March 2022 and that bit of code hasn't changed since. This is all very mysterious.

**Comment by jim-easterbrook** [comment]
Aha! If I install an old version of `cachetools`, e.g. `pip install "cachetools<4"`, then run Photini and do a map search, it creates a `'pkl` cache file that I assume refers to `cachetools.ttl`. Updating `cachetools` to v5.3.3 then gives me unloadable map tabs, but without the helpful error log you got.

Try deleting the `.pkl` files in `~/.cache/photini/`, then update `cachetools`, then run Photini.

**Comment by jlprojects** [comment]
I recall having problems when upgrading my system to OpenSuse 15.6 - but I'm unsure how I fixed it. Probably by using a system cachetools library - so that was the workaround then.  Root cause looks an out of date bit of cruft in the .cache/photini folder.

Again thanks for a very useful piece of software and quick resolution. :+1:

**Comment by jim-easterbrook** [comment]
I've made the cache loading a bit more robust against errors like this. Thanks again for reporting the problem.

**Comment by jlprojects** [comment]
Thanks again. :smiley:
