### ISSUE TITLE
Ask for view multiple regions

### ISSUE THREAD

**Issue by regexgit** [jim-easterbrook/Photini#250]
The attached image is taken from an old application for describing Romanesque sculptures: XMP didn't yet exist and the coordinates of the regions and the associated descriptions were stored in an external database.

When I discovered the existence of the ‘Image region’ field I said to myself: ‘great, I don't need databases any more, I'll store the information in the image itself’.

I immediately started reproducing the original image in Photini but it's not very easy because each new region is drawn on a blank image, there's a risk of overlapping with the previous regions, and I have to switch between the region tabs often: would it be possible to see all the regions already drawn (with a different colour to the current one) ?

![P3070686_zones](https://github.com/user-attachments/assets/5434c109-ae84-4243-a321-44a55dcd8360)

**Comment by jim-easterbrook** [comment]
That's a good idea. I'll have a go at doing it this week.

**Comment by jim-easterbrook** [comment]
If your old database is readable from a Python script you could use Photini's metadata handling to copy it directly. Something like this (completely untested).
```
from photini.metadata import Metadata

md = Metadata(image_file_path)
for polygon in data_base:
    vertices = []
    for vertex in polygon:
        vertices.append({'Iptc4xmpExt:rbX': vertex['x'],
                         'Iptc4xmpExt:rbY': vertex['y'})
    boundary = {'Iptc4xmpExt:rbShape': 'polygon',
                'Iptc4xmpExt:rbUnit': 'relative',
                'Iptc4xmpExt:rbVertices': vertices}
    region = {'Iptc4xmpExt:RegionBoundary': boundary}
    md.image_region = md.image_region.new_region(region)
md.save()
```

**Comment by jim-easterbrook** [comment]
Documentation of next release's image regions. See pictures towards the bottom of the page.
https://photini.readthedocs.io/en/latest/manual/regions.html

**Comment by regexgit** [comment]
More on colors:

Here's an example where the regions are invisible:
![tympan_grey](https://github.com/user-attachments/assets/794f3c3c-227f-456e-b853-954af84cbbad)


I've patched the code to replace “lightGray” with “black”, which is already better:
![tympan_black](https://github.com/user-attachments/assets/b7c81e27-6eaa-44ba-9890-b59a1d4d03d1)


But the regions are the stars of the feature, why hide them? and I've gone straight to red, I'm very happy with it, I'm going to keep this patch!
![tympan_red](https://github.com/user-attachments/assets/cccbf9f4-d275-44af-be3e-c91b1f5579b6)

**Comment by jim-easterbrook** [comment]
Grey was never a great choice, and red looks grey to 1 in 12 male humans! I'm currently using alternating blue/yellow which seems to contrast well with many images (sky, buildings, etc.) and probably works for most colour blind people.

**Comment by regexgit** [comment]
My point was mainly to avoid grey but we agree on that point.
As for the color I am not an ayatollah of red either, I am sure you will find a wonderful yellow or a splendid blue.

**Comment by regexgit** [comment]
I'll go back: I tested your code exemple by adding just one datum:
```
from photini.metadata import Metadata

polygon1 = [ {'x': 0.2, 'y': 0.2},   {'x': 0.4, 'y': 0.2}, {'x': 0.4, 'y': 0.4},]
database = [polygon1]
image_file_path = '/home/gto/applis/photo/photini2/photos_test/panasonic_orig.JPG'

md = Metadata(image_file_path)
for polygon in database:
	vertices = []
	for vertex in polygon:
		vertices.append({'Iptc4xmpExt:rbX': vertex['x'],
							  'Iptc4xmpExt:rbY': vertex['y']})
		boundary = {'Iptc4xmpExt:rbShape': 'polygon',
						'Iptc4xmpExt:rbUnit': 'relative',
					 	'Iptc4xmpExt:rbVertices': vertices}
		region = {'Iptc4xmpExt:RegionBoundary': boundary}
		md.image_region = md.image_region.new_region(region)
md.save()
``` 
and got errors:
```
XMP Toolkit error 102: Unknown namespace prefix for qualified name
Failed to encode XMP metadata.
panasonic_orig.JPG: tag not saved: Xmp.iptcExt.ImageRegion
...
```
for all XMP fields (not only Xmp.iptcExt.ImageRegion)

Something must be missing !

**Comment by regexgit** [comment]
Thanks, it works perfectly with MetadataHandler

**Comment by regexgit** [comment]
There was a big mess in the indentations when I copied my code, here's the exact code if anyone wants to use it:
```
from photini.metadata import Metadata
from photini.exiv2 import MetadataHandler
MetadataHandler.initialise(None, 0)

polygon1 = [ {'x': 0.2, 'y': 0.2},   {'x': 0.4, 'y': 0.2}, {'x': 0.4, 'y': 0.4},]
database = [polygon1]

md = Metadata(image_file_path)
for polygon in database:
    vertices = []
    for vertex in polygon:
        vertices.append({'Iptc4xmpExt:rbX': vertex['x'],
                         'Iptc4xmpExt:rbY': vertex['y']})
    boundary = {'Iptc4xmpExt:rbShape': 'polygon',
                'Iptc4xmpExt:rbUnit': 'relative',
                'Iptc4xmpExt:rbVertices': vertices}
    region = {'Iptc4xmpExt:RegionBoundary': boundary}
    md.image_region = md.image_region.new_region(region)
md.save()
```
