### ISSUE TITLE
Map (Mapbox) error

### ISSUE THREAD

**Issue by regexgit** [jim-easterbrook/Photini#254]
After 2024.8.0 migration I get the following error on mapbox (google and Bing OK):

```
==== version info ====
Photini 2024.8.0
  Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
  python-exiv2 0.17.0, exiv2 0.28.3
  PySide6 6.7.2, Qt 6.7.2
  system locale fr, locales: fr-FR fr-Latn-FR fr
  styles: Windows, Fusion
  using style: fusion
==== messages ====
22:40:47: ERROR: photini.photinimap: https://api.mapbox.com/mapbox-gl-js/v3.4.0/mapbox-gl.js line 31: Error: Failed to initialize WebGL
22:40:47: ERROR: photini.photinimap: https://api.mapbox.com/mapbox-gl-js/v3.4.0/mapbox-gl.js line 45: Uncaught Error: Failed to initialize WebGL.
==== end ====
```

**Comment by jim-easterbrook** [comment]
One more test: start Photini with high verbosity (`photini -vvv`) and find what user agent it reports. Mine is `photini.photinimap: user agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/6.7.2 Chrome/118.0.5993.220 Safari/537.36`.

**Comment by jim-easterbrook** [comment]
Aha! I can reproduce the error if I add this to the `photinimap.py` file:
```
        settings.setAttribute(
            settings.WebAttribute.WebGLEnabled, False)
```
The Qt documentation of `WebGLEnabled` says "Enables support for HTML 5 WebGL. Enabled by default if available. (Added in Qt 5.7)"

This suggests `WebGL` is not available on your system.

**Comment by jim-easterbrook** [comment]
Can you try editing your `photinimap.py` file (it's probably sommewhere like `~/.local/lib/python3.11/site-packages/photini/photinimap.py`) and adding this line after line 169:
```
        settings.setAttribute(settings.WebAttribute.WebGLEnabled, True)
```
If this fixes the problem I'll do a new release with it added.

**Comment by jim-easterbrook** [comment]
See also https://doc.qt.io/qt-6/qtwebengine-features.html#webgl
"Qt WebEngine supports WebGL for some graphics stacks setups."
That word "some" is worrying. Support appears to depend on a lot of things, such as graphics driver capabilities, so it's not obvious how Photini should detect if WebGL can be used, or what to do if it can't.

**Comment by jim-easterbrook** [comment]
This looks promising.
https://docs.mapbox.com/help/tutorials/use-mapbox-js-as-fallback/

**Comment by jim-easterbrook** [comment]
New release 2024.8.1 reverts to the old Mapbox map if WebGL is not available.

**Comment by regexgit** [comment]
Wow, you're releasing versions at the speed of light

**Comment by jim-easterbrook** [comment]
You've got me at a good time. The maps stuff is still fresh in my mind so it's not too hard to resume working on it. I assume the fix works for you then.

**Comment by regexgit** [comment]
Yes it works.

> I think PyQt is generally better than PySide. 

Ah! good to know, I searched for a long time on the internet to find out which one to install but I only found very consensual opinions, so I chose PySide at random.
Next time I'll install PyQt

**Comment by jim-easterbrook** [comment]
There's unlikely to be any problem caused by installing more than one Qt library - I usually have all four installed. Then using `photini-configure` to switch between them is reasonably quick.

There's not a lot of difference really, but PyQt has a few small advantages. On the programming side it understands Python buffer interfaces so you don't need to copy data to `bytes` before passing it to a Qt function.

My main complaint about PySide is that it uses 32-bit floats. If you type latitude and longitude values into a map tab's widget you might find that the values get changed slightly. (Dragging an icon on the map is different, as the widget is updated with text values rather than going through Qt's string to float conversion.)
