### ISSUE TITLE
Colour blindness compatibility

### ISSUE THREAD

**Issue by jim-easterbrook** [jim-easterbrook/Photini#263]
Photini ought to be usable by colour blind people - they can see clearly, but not distinguish certain colours, so are just as likely to take photos as anyone else.

I've found a colour blindness simulator (https://www.color-blindness.com/coblis-color-blindness-simulator/) which shows Photini's use of a red border to show which image is selected is a very bad choice.

I'm sure there are more problems to be found. If any Photini user with colour vision deficiency sees this, I'd welcome any feedback on where Photini presents problems.

**Comment by jim-easterbrook** [comment]
I've created a new branch bug_263 for this work.

**Comment by regexgit** [comment]
I like red, it's the most visible color. It's good to think of the colour blind people but on condition that others aren't penalized: I'd like a configuration file that lets us choose the colors.

**Comment by jim-easterbrook** [comment]
My current plan is to allow users to choose any colours they like for the map markers, as there is no obvious choice of colour that suits all map styles (including aerial photos) and all colour vision abilities.

The selected image thumbnail highlighting will use the same colour scheme as selecting text in one of the text entry boxes. This gives a more consistent look and feel, and colour blind users will probably already have configured their computer's colour palette.
