### ISSUE TITLE
Image viewer - external/internal

### ISSUE THREAD

**Issue by regexgit** [jim-easterbrook/Photini#268]
The thumbnails are unusable for my bird photos - too small - so I have to systematically open them in the external viewer, but it opens each time in a new window and I end up with lots of useless windows because I don't always think to close them.

Would it be possible for photini to launch a single instance of the viewer?

As I was fed up, I found another solution: look at the image in the "Image regions" tab ((which I know well ...) with photini full screen (by the way, the image doesn't enlarge itself when enlarging the window, you have to reload the image).

It works but it's not practical, in full screen it's less easy to drag/drop the photos from the explorer and I can't control the magnification ratio.

And so I'll end with a suggestion: why not a very simple "viewer" tab with just a zoom button?

**Comment by jim-easterbrook** [comment]
I don't think Photini can do anything about the viewer - it's an external program launched by `QtGui.QDesktopServices.openUrl` (https://doc-snapshots.qt.io/qt6-6.2/qdesktopservices.html#openUrl). I simply use the viewer's controls to change to the image I want to look at, using the file names to make sure the viewer and Photini are looking at the same file.

I have ensured there's only one instance of Photini running, so you might be able to choose an image in your image viewer, then right-click and select "open with Photini". When you've finished editing it in Photini, close the image so Photini has no images open. Then select the next image of interest in the viewer and repeat. (This assumes you've run `photini-post-install` to associate Photini with image files.)

I could improve this process by making Photini select the image if you do the 'right-click' thing and it already has the image open.

The image not enlarging when the window size changes is a bug which I can easily fix.

Thanks for these suggestions. Keep 'em coming!

**Comment by jim-easterbrook** [comment]
> The image not enlarging when the window size changes is a bug which I can easily fix.

Actually it turns out to be rather more difficult than I'd thought. I don't want to simply recalculate and apply the optimum zoom as the user may have already zoomed in. The window shape may also change, which complicates things.

As the regions window is now zoomable I think it's easier to leave it up to the user. Resizing the window reveals more of a zoomed in image, keeping it the same size, and I think that looks OK.

**Comment by regexgit** [comment]
No, thanks for the suggestion, but this workflow doesn't work for me.

But let's get back to zooming with a real-life example:

**Step 1**: small Photini window with unreadable thumbnail and image too small

![windows_1_elanion](https://github.com/user-attachments/assets/f27cdf81-82e6-466a-a854-3b47704d4669)




**Step 2**: photini window in full screen to enlarge the image as much as possible

![windows_2_elanion](https://github.com/user-attachments/assets/dac94b73-a606-4ea3-bbb7-20215d8d2ccc)




**Step 3**: Photini reduction to the initial size (as step 1), the image has not changed size, so you'll agree that we have indeed zoomed in the small window.

![windows_3_elanion](https://github.com/user-attachments/assets/fbfd217c-d07d-4c0b-a7c1-cdc29c33f7cf)



What would work for me is to go from step 1 to step 3 without going through step 2, with a ‘zoom’ button.

**Comment by regexgit** [comment]
And in case you didn't recognise it, it's a black-winged kite !

**Comment by jim-easterbrook** [comment]
The regions tab is zoomable in the next release. (Commit 9d61836.)
