### ISSUE TITLE
Google Photos not working

### ISSUE THREAD

**Issue by waorak** [jim-easterbrook/Photini#27]
Google Photos doesn't seem to be working. The connection button opens Google Photos and once signed in, Google generates the code to paste into the program. Once the code is pasted into the Photini dialog, it seems to just hang. After restarting Photini, the Connect button changes to Logout, but the User frame still gives the status as not connected. 

Win10, 64bit, installer and then ran the update too. Google account is using two factor authentication. Flickr account works fine.

Thank you
Russell

**Comment by jim-easterbrook** [comment]
Google have recently disabled a large chunk of the Picasa API (see #22) so this may be related. I don't have time to investigate it now, but might be able to look into it in a few days time.

**Comment by jim-easterbrook** [comment]
I've done a bit of investigation and have discovered that there's been a change in the 'requests' Python library that causes problems with an additional header required by the Google Photos API. Can you run Photini from a command window (see http://photini.readthedocs.io/en/latest/other/installation.html#troubleshooting) and see if you get any messages like `requests.exceptions.InvalidHeader: Header value 2 must be of type str or bytes, not <class 'int'>`.

This isn't the only problem though, as downgrading versions of the 'requests' library (and associated libraries) gives me certificate verification failure on Windows 7 (the only version I have access to) but not on Linux.

Given the newly crippled state of the Google Photos API (e.g. can no longer create albums!) I'm not sure it's worth trying to get it working until Google come up with a useful replacement.

**Comment by jim-easterbrook** [comment]
I think I've sorted out the certificate verification problem in commit 0623aa1. I can log in and out of Google Photos on Linux and Windows 7 and get the same crippled functionality on each.

**Comment by jim-easterbrook** [comment]
The latest release 2017.03.0 incorporates these changes. Please let me know if it works for you.

**Comment by jim-easterbrook** [comment]
@waorak Have you tried the latest version yet?
