### ISSUE TITLE
Extending Photini

### ISSUE THREAD

**Issue by regexgit** [jim-easterbrook/Photini#280]
The documentation suggests that it is possible to extend photini by adding tabs. That's easy, but when you start playing with the metadata you realise that the exiv2 module is just an overlay on the real exiv2 module, which is confusing.

I've had a look at the code but it's not easy to find the entry points, some APIs are missing. 

Would it be possible to complete the documentation on this subject ? (but I know documentation isn't the most fun part of being a developer !)

**Comment by jim-easterbrook** [comment]
The possibility of extending Photini is a bit of an afterthought, and I haven't really designed Photini to have much of an API. There's been a lot of evolution over the years, for example the `photini.exiv2` wrapper round `python-exiv2` was an alternative to a `photini.gexiv2` wrapper round `PyGObject`'s wrapper round `gexiv2`.

The `photini.metadata` module is a higher level interface and handles reading metadata from image file and/or sidecar and so on. It defines names such as `date_taken` and links them to multiple exiv2 keys. This is where I've added new items for the hierarchical metadata.

Extending Photini by adding tabs uses a dynamically loaded extension module. This was a side effect of making some modules optional (hence Photini's optional dependencies).
