### ISSUE TITLE
Geotagging: grouping markers

### ISSUE THREAD

**Issue by regexgit** [jim-easterbrook/Photini#282]
During a trip I photographed the same subject several times at different times.
When I geotagged my photos, the thumbnails of this subject didn't follow each other, so I was forced to place a marker each time I encountered this subject.
In the end I've got a big bunch of markers in the same location that I'd like to group together into a single marker.

What I'd like:

- when placing one marker on another, merge the markers if they're very close.

- to be able to select several markers with Ctrl click, as with thumbnails, in which case you can zoom in to separate neighboring markers, select them all and move a photo of the group to the same location.

**Comment by jim-easterbrook** [comment]
> What I'd like:
> 
>     * when placing one marker on another, merge the markers if they're very close.

Close in pixels on the screen or metres on the ground? I can see this being a nuisance if one doesn't want to merge the markers.

>     * to be able to select several markers with Ctrl click, as with thumbnails, in which case you can zoom in to separate neighboring markers, select them all and move a photo of the group to the same location.

This ctrl-click idea is good, and consistent with the rest of the user interface. Having selected multiple locations you can just right-click on the coordinates display to choose one of them. With very close markers it might still be difficult to ctrl-click on the unselected one as it's "behind" a selected one, and the click area is usually a rectangle that covers more than the visible marker. I'd also need to check that the JavaScript map libraries I'm using all include the ctrl modifier in their click events.

What I do at present in this situation is as follows:
1/ select one of the thumbnails.
2/ click on the coordinates display, ctrl-a, ctrl-c to copy the coords.
3/ select one of the "other" thumbnails.
4/ click on the marker to select all images at that location.
5/ click on the coordinates display, ctrl-a, ctrl-v, return to paste the coords.

**Comment by jim-easterbrook** [comment]
> With very close markers it might still be difficult to ctrl-click on the unselected one as it's "behind" a selected one, and the click area is usually a rectangle that covers more than the visible marker.

The solution to this is probably for an already selected marker to ignore the 'ctrl-click' event so it propagates to the marker behind it. If that's possible.

**Comment by jim-easterbrook** [comment]
Experiments with the Azure map are not very promising. It needs monitoring of key presses and releases to track if the control key is down when the mouse is clicked. I haven't found a way of getting a selected marker to send the click event to an unselected one behind it.

**Comment by jim-easterbrook** [comment]
Another option, which I can implement in Python so will be the same for all maps, is to have repeated clicks (within the system double click interval) select the next nearest marker. This is analogous to word processors where a double click selects a word, a triple click selects a sentence, and a quadruple click selects a paragraph.

**Comment by regexgit** [comment]
> Close in pixels on the screen or metres on the ground? I can see this being a nuisance if one doesn't want to merge the markers.

I don't see how this could happen: if you want to place 2 markers in 2 different places, simply increase the zoom. Placing one marker on top of another is the natural way of saying “I want these 2 markers to be in the same place”. This is how diagram drawing software works: when you drop one object on top of another, they are automatically linked, whatever the scale of the drawing.

> What I do at present in this situation is as follows:

Yes, this workaround works, I do things a little differently because I don't know the thumbails associated with the location so I only select the markers:

1/ select one of the thumbnails.
2/ click on the coordinates display, ctrl-a, ctrl-c to copy the coords.
3/ select one of the other marker.
4/ click on the coordinates display, ctrl-a, ctrl-v, return to paste the coords.

> Another option ... repeated clicks

Yes, I like it

**Comment by jim-easterbrook** [comment]
> simply increase the zoom

All the maps have a maximum zoom level which can still leave markers overlapping. The problem I anticipate with "snap to grid" type behaviour is undoing it if it happens accidentally. Clicking on the marker will select all the images, so picking out the ones you didn't want there from the ones you did may not be easy.

It's also tricky to implement. Python knows nothing about pixels on the map, JavaScript knows nothing about allocated images.

**Comment by jim-easterbrook** [comment]
Counting clicks is not made any easier when maps have stuff like this in their API docs:
> This event is fired when the user double-clicks on the map. Note that the click event will sometimes fire once and sometimes twice, right before this one.

**Comment by jim-easterbrook** [comment]
Now available in release 2024.10.0
