### ISSUE TITLE
Photo file modification date

### ISSUE THREAD

**Issue by regexgit** [jim-easterbrook/Photini#283]
I just noticed that Photini changes the file date after modification, could we have a configuration option to keep the original date ?

**Comment by jim-easterbrook** [comment]
I refer the honourable gentleman to the documentation, particularly the bit about file timestamps.https://photini.readthedocs.io/en/latest/manual/configuration.htmlOn 29 Sept 2024 15:38, Gérard Toulgoat ***@***.***> wrote:
I just noticed that Photini changes the file date after modification, could we have a configuration option to keep the original date ?

**Comment by regexgit** [comment]
Shame of me !!!
