### ISSUE TITLE
Problem with special chars in filename

### ISSUE THREAD

**Issue by salvadhor** [jim-easterbrook/Photini#32]
Photini fails to copy imported photos when there's special character in filename. In my case it was space ' '. 

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/photini/importer.py", line 510, in copy_selected
    copy_list.append(self.file_data[name])
KeyError: u'Reflectionintheyukon'

Original filename:

Reflectionintheyukon - 2880x1800 300ppi (Large).jpg

**Comment by jim-easterbrook** [comment]
Thanks for reporting that - I hadn't considered importing files with spaces in their names, as cameras generally don't do that.

**Comment by jim-easterbrook** [comment]
I've released version 2017.8.1 which includes the fix.
