### ISSUE TITLE
Strange warning on console

### ISSUE THREAD

**Issue by luigino** [jim-easterbrook/Photini#37]
When launching from command-line, I see this (number varies at times):
```
~> photini 
[0425/183515.033821:WARNING:stack_trace_posix.cc(648)] Failed to open file: /home/user/#29701 (deleted)
  Error: No such file or directory
```

**Comment by jim-easterbrook** [comment]
Yes, I'm getting that as well when using QtWebEngine. I think the number is a process id. I did a Google search and it appears to be related to the Chromium browser.
Another example (a PyQt based web browser): https://github.com/qutebrowser/qutebrowser/issues/3459

**Comment by luigino** [comment]
I thought the same, only it's not in the process list.

If it comes from QtWebEngine, I suppose it has to be reported somewhere else.

**Comment by The-Compiler** [comment]
Someone reported this upstream as [QTBUG-68547](https://bugreports.qt.io/browse/QTBUG-68547).
