### ISSUE TITLE
Could the catalan translation added to photini?

### ISSUE THREAD

**Issue by aseques** [jim-easterbrook/Photini#42]
I just completed the translation for the photini interface (docs are WIP) in transifex, could you add them to the next release?

**Comment by jim-easterbrook** [comment]
Thank you, and I'll certainly add Catalan to the next release. (I try to remember to check Transifex for new / updated translations before every release.)

**Comment by jim-easterbrook** [comment]
What name should I credit the Catalan translation to?

**Comment by aseques** [comment]
Oh, Joan Juvanteny, thanks
