### ISSUE TITLE
type object 'Metadata' has no attribute 'find_side_car'

### ISSUE THREAD

**Issue by aseques** [jim-easterbrook/Photini#46]
I'm on current git as of 06/10/2019, and I'm getting these errors for the first time. I am trying to import regular photos (they aren't videos or anything special)
> 22:41:35: ERROR: photini.pyqt: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/photini/pyqt.py", line 105, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python3.7/dist-packages/photini/importer.py", line 364, in new_source
    self.source, self.config_section = item_data
TypeError: cannot unpack non-iterable NoneType object
22:44:09: ERROR: photini.importer: type object 'Metadata' has no attribute 'find_side_car'
22:45:58: ERROR: photini.importer: type object 'Metadata' has no attribute 'find_side_car'
22:46:34: ERROR: photini.importer: type object 'Metadata' has no attribute 'find_side_car'
22:46:46: ERROR: photini.importer: type object 'Metadata' has no attribute 'find_side_car'

**Comment by jim-easterbrook** [comment]
Ah, thanks for that. A bug in my recent changes that I hadn't found. I'll fix it asap.

**Comment by jim-easterbrook** [comment]
Commit d72f98c should fix this. Sorry for the inconvenience.

**Comment by aseques** [comment]
No problem, glad to help

**Comment by aseques** [comment]
It's working normally again, thanks
