### ISSUE TITLE
Version mismatch between git tag and setuptools

### ISSUE THREAD

**Issue by lgbaldoni** [jim-easterbrook/Photini#57]
See https://github.com/jim-easterbrook/Photini/blob/2020.12.1/src/photini/__init__.py#L3

**Comment by jim-easterbrook** [comment]
Doh! Thanks for letting me know. It probably isn't worth doing a new release just to fix this.

**Comment by jim-easterbrook** [comment]
However, I've just discovered some PySide2 incompatibilities I'd missed, so a new release may not be too far away.

**Comment by jim-easterbrook** [comment]
I've just released version 2020.12.2 - this should have the right version numbers everywhere.
