### ISSUE TITLE
Better DateTimeEdit handling

### ISSUE THREAD

**Issue by LordCatzorz** [jim-easterbrook/Photini#58]
Hi,

When I try to use the datetime editors (Technical Metadata), I find myself trying to use some pattern that the edit does not allow.

---

### Can not edit with two date component selected
With an edit with day precision and a date, select the months and the day. Typing a new month/day (ex: 0601) does not change anything in the edit. The texts stays selected. 
I would like to be able to have a date, ex: 1994-01-01 select both months and day, type 0 6 0 1 on my keyboard and have the final date set to 1994-06-01
![image](https://user-images.githubusercontent.com/4494468/101990184-72cee780-3c73-11eb-95d1-331024aa4073.png)

### Can not replace date without selecting the whole year
With an edit with day precision and a date, place your cursor at the beginning. Typing a new date (ex:1994-06-01) does not change anything in the edit. The cursor stays at its position.
I would like to be able to enter a new date without having to select the whole year. Only then will I be able to enter a new date manually.

---

I've been looking the add those behaviours, but I have never really worked with QT, so I'm not even sure it's possible.

Thank you.

**Comment by jim-easterbrook** [comment]
I'm not sure it's possible either. (And I'm reluctant to make too many modifications to Qt widget behaviour, even if I knew how.) However, if you just select the month, then type 0601, I think it does what you want.

**Comment by LordCatzorz** [comment]
Alrighty!

I'll train my brain to adapt to this behaviour :wink:

Thanks anyway!
