### ISSUE TITLE
Automatically generate thumbnails for png images

### ISSUE THREAD

**Issue by cweiske** [jim-easterbrook/Photini#59]
I wanted to add titles to 20 .png images, and ran photini on command line with their names:

```
$ photini *.png
```

Then the photini main window was visible with all the images, but they had no thumbnail.
I could manually right-click on each of them and press "refresh thumbnail", but I would have to do this for each of them. (Marking multiple and then triggering thumb refresh does not work).

It would be nice if photini would automatically create thumbnails, or at least would allow refreshing them for many at once.

----

```
Photini 2020.12.2, build 1583 (b861ef1)
  Python 3.8.6 (default, Sep 25 2020, 09:36:53) 
[GCC 10.2.0]
  PyGObject 3.38.0, GExiv2 0.12.1, GObject 2.0, GLib 2.66.0
  PyQt 5.15.1, Qt 5.15.1, using QtWebEngine
  ffmpeg version 4.3.1-5 Copyright (c) 2000-2020 the FFmpeg developers
  available styles: qt5ct-style, Windows, Fusion
  using style: qt5ct-style
```

**Comment by jim-easterbrook** [comment]
Good idea. I think it should also apply to other things on the image selector context menu such as reload metadata. I'm not keen on automatically doing anything, as my general philosophy is only make changes that the user requests.

I'll work on it for the next release, sometime after Christmas.

**Comment by cweiske** [comment]
Thanks, that works fine now!
