### ISSUE TITLE
Ability to change UI scale 

### ISSUE THREAD

**Issue by Mohammad-Asiri** [jim-easterbrook/Photini#62]
Hi,

Is there a way to increase the UI scale for higher resolution monitors?

At the moment when I run Photini the current UI is hard on the eyes, as the screenshot shows.

Thank

![Screenshot from 2021-10-19 15-26-07](https://user-images.githubusercontent.com/11486417/137909017-e9b9d0bf-cea9-47b3-a6d2-4dfba5fb848a.png)
s.

**Comment by jim-easterbrook** [comment]
New release 2021.11.0 has a `qt_scale_factor` option in the Photini config file.

**Comment by Mohammad-Asiri** [comment]
> New release 2021.11.0 has a `qt_scale_factor` option in the Photini config file.

Hi Jim,

I just installed the new version, and it is now really clear and viewable.

Thanks a lot for your hard work.

**Comment by jim-easterbrook** [comment]
Do let me know if you find anything that's still the wrong size.
